language: android

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra
    - addon
    - android-22
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-22

jdk:
  - oraclejdk8
before_script:
  - pwd
  - chmod +x gradlew
  - mkdir -p /home/travis/sdcard/
  - mksdcard -l baldphonesdcard 128M /home/travis/sdcard/sdcard.img
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window -camera-back none -camera-front none -no-boot-anim -sdcard /home/travis/sdcard/sdcard.img -no-snapshot-save &
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell pm disable com.android.launcher
  - ./gradlew assemblebaldUpdatesDebug
  - ./gradlew installbaldUpdatesDebug
  - adb shell settings put secure enabled_notification_listeners %nlisteners:com.bald.uriah.baldphone/com.bald.uriah.baldphone.services.NotificationListenerService
  - adb shell ime enable com.bald.uriah.baldphone/.keyboard.BaldInputMethodService
  - adb shell ime set com.bald.uriah.baldphone/.keyboard.BaldInputMethodService

  - adb shell input keyevent 82 &
script:
  - ./gradlew connectedbaldUpdatesDebugAndroidTest
  - cd /home/travis
  - git clone https://github.com/UriahShaulMandel/BaldPhoneCompanion.git --depth 1
  - cd BaldPhoneCompanion
  - git config user.email "baldphone.contact@gmail.com"
  - git config user.name "BaldPhoneTravis"
  - mkdir -p /home/travis/BaldPhoneCompanion/screenshots
  - adb pull /sdcard/Pictures/screenshots /home/travis/BaldPhoneCompanion/screenshots
  - branch_name=`git branch | grep \* | cut -d ' ' -f2`
  - folder_name="/home/travis/BaldPhoneCompanion/apks/$branch_name"
  - file_name="/home/travis/BaldPhoneCompanion/apks/$branch_name/tmp_apk.apk"
  - mkdir -p "$folder_name"
  - cp /home/travis/build/UriahShaulMandel/BaldPhone/app/build/outputs/apk/baldUpdates/debug/app-baldUpdates-debug.apk "$file_name"
  - curl http://baldphone.c1.biz/users_track_json.php -o /home/travis/BaldPhoneCompanion/users.json
  - curl http://baldphone.c1.biz/downloads_track_json.php -o /home/travis/BaldPhoneCompanion/users_track.json
  - git add --all :/
  - git commit -am "$TRAVIS_COMMIT"
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then git push https://UriahShaulMandel:${GITHUB_API_KEY}@${GH_REF} HEAD:master; fi'

before_install:
  - echo yes | android update sdk --all --filter build-tools-28.0.3 --no-ui --force
dd:
  secure: kp7Bw9boFlD2Zq2W4pZi2FNscbdjG0jskAtESep/vuldrRz/3H6xFXtuWpZg6YXlAVn5mx6jMVQl8j+hw+NLgQ7BktSmhrNgoXIgQ2ZGjsv2pu3VrLGz57chD7hgeNGLaDr9SSFu3AElI6hCJuXjgkyDSATRG4F+IQ/3NT1twg7oArzYVfH6atGdtTljeuaEet2+6fIVoIcuQ0WgkorH7Kem/TGNiuSqzA6wNL2FQSL2Ff+hloFhbmHdeYh6glxhZltygOKRfxsFbDn7WBkCi/xh+F7FWZve5CTEmeGiw49z3Ydjh8IUkWmw+1LMqM0zQo2P88a1rIZlViXR9y8wI98YYvhMQPKmgQ5DSKl1WBVjBl0AxE/ou419iCQnIiB2KCUZn6UwPEvxBD7qSo6QInZVdMr6K+bKRYpsCi1BjARoJ7qqHVNajQOmL0qwXVuLnvKArNxN0DVFsUG1VqVVfw04EXXkC19Kl8mVvsBTxYdzdAsvuZZiQ4vse4K9L+kOWexVDPNhSNPSKhbG0sNFh09buIz1Pe7r4hTHEoYzlilRkG5W1YtiU9cp93a4MrC5wZ3WQ3z3IpBARmA9ehVQZyRzxDxpt7PJiuXqT8Ojdq6RY39b3CrOcwJkmPiu1vSOUC+Jj7+7pWykIQMbbubN0LspbZgNnff2YAse8FS8XuQ=

